ALTER TABLE staff ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'manual';
ALTER TABLE staff ADD COLUMN IF NOT EXISTS crm_id INTEGER;
CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_crm_id ON staff(crm_id) WHERE crm_id IS NOT NULL;