ALTER TABLE t_p93118852_lineaschool_initiati.booking_links
    ADD COLUMN IF NOT EXISTS parent_name VARCHAR(200) DEFAULT '',
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50) DEFAULT '',
    ADD COLUMN IF NOT EXISTS child_name VARCHAR(200) DEFAULT '',
    ADD COLUMN IF NOT EXISTS max_bookings INTEGER NOT NULL DEFAULT 1;
